---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UserListResponse"
    post:
      summary: create user
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Errors"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                full_name:
                  type: string
              required:
              - email
              - full_name
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/User"
        '404':
          description: not found
    put:
      summary: update user
      parameters: []
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/User"
        '404':
          description: not found
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Errors"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                full_name:
                  type: string
              required:
              - email
              - full_name
    delete:
      summary: delete user
      responses:
        '204':
          description: no content
        '404':
          description: not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  schemas:
    UserListResponse:
      type: object
      properties:
        users:
          type: array
          items:
            "$ref": "#/components/schemas/User"
        meta:
          "$ref": "#/components/schemas/ListMeta"
    ListMeta:
      type: object
      properties:
        total_count:
          type: integer
    User:
      type: object
      properties:
        email:
          type: string
        full_name:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              attribute:
                type: string
              messages:
                type: array
                items:
                  type: string
