---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/courses":
    get:
      summary: list courses
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/CourseListResponse"
    post:
      summary: create course
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Course"
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Errors"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                author_id:
                  type: integer
                skill_slugs:
                  type: array
                  items:
                    type: string
              required:
              - title
              - description
  "/api/v1/courses/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show course
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Course"
        '404':
          description: not found
    put:
      summary: update course
      parameters: []
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Course"
        '404':
          description: not found
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Errors"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                skill_slugs:
                  type: array
                  items:
                    type: string
              required:
              - title
              - description
    delete:
      summary: delete course
      responses:
        '204':
          description: no content
        '404':
          description: not found
  "/api/v1/courses/{id}/remove_author":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: remove author
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Course"
        '404':
          description: not found
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Errors"
  "/api/v1/skills":
    get:
      summary: list skills
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SkillListResponse"
    post:
      summary: create skill
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Skill"
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Errors"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                slug:
                  type: string
              required:
              - name
              - slug
  "/api/v1/skills/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show skill
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Skill"
        '404':
          description: not found
    put:
      summary: update skill
      parameters: []
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Skill"
        '404':
          description: not found
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Errors"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                slug:
                  type: string
              required:
              - name
              - slug
    delete:
      summary: delete skill
      responses:
        '204':
          description: no content
        '404':
          description: not found
  "/api/v1/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UserListResponse"
    post:
      summary: create user
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Errors"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                full_name:
                  type: string
              required:
              - email
              - full_name
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/User"
        '404':
          description: not found
    put:
      summary: update user
      parameters: []
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/User"
        '404':
          description: not found
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Errors"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                full_name:
                  type: string
              required:
              - email
              - full_name
    delete:
      summary: delete user
      responses:
        '204':
          description: no content
        '404':
          description: not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  schemas:
    UserListResponse:
      type: object
      properties:
        users:
          type: array
          items:
            "$ref": "#/components/schemas/User"
        meta:
          "$ref": "#/components/schemas/ListMeta"
    ListMeta:
      type: object
      properties:
        total_count:
          type: integer
    User:
      type: object
      properties:
        email:
          type: string
        full_name:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              attribute:
                type: string
              messages:
                type: array
                items:
                  type: string
    SkillListResponse:
      type: object
      properties:
        skills:
          type: array
          items:
            "$ref": "#/components/schemas/Skill"
        meta:
          "$ref": "#/components/schemas/ListMeta"
    Skill:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        slug:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    CourseListResponse:
      type: object
      properties:
        courses:
          type: array
          items:
            "$ref": "#/components/schemas/Course"
        meta:
          "$ref": "#/components/schemas/ListMeta"
    Course:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        author:
          "$ref": "#/components/schemas/User"
        skills:
          type: array
          items:
            "$ref": "#/components/schemas/Skill"
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
